#!/usr/bin/env python

import os
import sys
from dataclasses import dataclass

@dataclass
class Config:
    wallh_api_key: str
    wallh_api_url: str


def set_defaults():
    Config.wallh_api_key = ''
    Config.wallh_api_url = ''


def main():
    set_defaults()


if __name__ == "__main__":
    main()
